//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeVMTests.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Resume_DBEntities : DbContext
    {
        public Resume_DBEntities()
            : base("name=Resume_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalInfo> AdditionalInfo { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CheckedResumeUsers> CheckedResumeUsers { get; set; }
        public virtual DbSet<EducationGrade> EducationGrade { get; set; }
        public virtual DbSet<EducationPlace> EducationPlace { get; set; }
        public virtual DbSet<EmployersInfo> EmployersInfo { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<LinkForPhoto> LinkForPhoto { get; set; }
        public virtual DbSet<PreviousJobs> PreviousJobs { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SearchersInfo> SearchersInfo { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserCategories> UserCategories { get; set; }
        public virtual DbSet<UserComputerSkills> UserComputerSkills { get; set; }
        public virtual DbSet<UserCourses> UserCourses { get; set; }
        public virtual DbSet<UserEducationGrade> UserEducationGrade { get; set; }
        public virtual DbSet<UserLanguages> UserLanguages { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
