//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer_skills
    {
        public int id_user { get; set; }
        public string first_field_computer_skills { get; set; }
        public string second_field_computer_skills { get; set; }
        public int first_level_of_computer_skill { get; set; }
        public int second_level_of_computer_skill { get; set; }
    
        public virtual Searchers_Info Searchers_Info { get; set; }
    }
}
