//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Searchers_Info
    {
        public int id_user { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public System.DateTime birthday { get; set; }
        public string family_status { get; set; }
        public string children { get; set; }
        public string army { get; set; }
        public string photo_link { get; set; }
    
        public virtual Additional_info Additional_info { get; set; }
        public virtual Computer_skills Computer_skills { get; set; }
        public virtual Cours Cours { get; set; }
        public virtual Education Education { get; set; }
        public virtual Language Language { get; set; }
        public virtual Previous_jobs Previous_jobs { get; set; }
    }
}
